# Site settings
title: TRAIN
email: MarkBruns@MarkBruns.com
description: Dogfooded training to onboard volunteers interested in developing the ecosystem of community communication apps
twitter_username: MarkBruns
github_username:  RockRapids

# Build settings
markdown: kramdown
